
default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: 123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_development

test:
  <<: *default
  database: shop_test
production:
  <<: *default
  database: shop_production
  username: root
  password: 123
